version: '3.7'

services:

    # Main components:
    #
    # - dnode (Dfinance Node) - Tendermint blockhain node which does all the storage-blocks-sync
    #   tasks. It's useless for manual operations unless wbcli is used to send transactions or
    #   read data via dnode s RPC endpoint.
    #
    # - dvm (Dfinance Move Virtual Machine) - no need to explain. :)
    #
    # You can play with them any way you want but keep in mind that:
    #
    # 1. Tendemint node ID is hardcoded into `./config/config.toml`, we've done it on purpose.
    #    Node ID there is our testnet bootnode which opened P2P port for you to sync with chain.
    #
    # 2. VM is a MUST, it's a server which executes code and responds to dnode with execution results
    #    Just keep it running - won't hurt.

    dvm:
        container_name: dvm
        image: ${REGISTRY_HOST:-registry.hub.docker.com}/${REGISTRY_GROUP:-dfinance}/dvm:${DVM_TAG:-latest}
        restart: always
        environment:
            DVM_LOG: error
        ports:
            - '127.0.0.1:9001:9001'   # metrics
            - '127.0.0.1:50051:50051' # compiler
        command: ./dvm -i 0.0.0.0:9001 "http://0.0.0.0:50051" "http://node:50052"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
                compress: "true"

    node:
        container_name: node
        depends_on: ["dvm"]
        image: ${REGISTRY_HOST:-registry.hub.docker.com}/${REGISTRY_GROUP:-dfinance}/dstation:${NODE_TAG:-latest}
        restart: always
        ports:
            - '${NODE_P2P_PORT:-26656}:26656' # p2p
            - '${NODE_REST_PORT:-127.0.0.1:1317}:1317' # rest
            - '${NODE_RPC_PORT:-127.0.0.1:26657}:26657' # rpc
        volumes:
            - ./entrypoint.sh:/entrypoint.sh
            - ./genesis:/tmp/genesis
            - ./config/.dstation:/root/.dstation/config
            - ./data:/root/.dstation/data
        environment:
            GENESIS_RPC_ENDPOINT: ${GENESIS_RPC_ENDPOINT}
            NODE_MONIKER: ${NODE_MONIKER:-my-first-dfinance-node}
            CHAIN_ID: ${CHAIN_ID}
            NODE_SEEDS: ${NODE_SEEDS}
            EXTERNAL_ADDRESS: ${EXTERNAL_ADDRESS}
            PERSISTENT_PEERS: ${PERSISTENT_PEERS}
            SEED_MODE: ${SEED_MODE}
        entrypoint: /entrypoint.sh
        command: ./dstation start --inv-check-period=50
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "5"
                compress: "true"
